{
  "formatVersion": "1.1",
  "component": {
    "group": "com.liferay",
    "module": "com.liferay.gradle.plugins.workspace",
    "version": "999.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "biz.aQute.bnd",
          "module": "biz.aQute.bnd.gradle",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.bmuschko",
          "module": "gradle-docker-plugin",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.github.docker-java",
          "module": "docker-java",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.ant.bnd",
          "version": {
            "requires": "3.2.10"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins",
          "version": {
            "requires": "14.0.169"
          },
          "excludes": [
            {
              "group": "biz.aQute.bnd",
              "module": "biz.aQute.bnd"
            }
          ]
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins.css.builder",
          "version": {
            "requires": "5.0.10"
          },
          "excludes": [
            {
              "group": "biz.aQute.bnd",
              "module": "biz.aQute.bnd"
            }
          ]
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins.poshi.runner",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "biz.aQute.bnd",
              "module": "biz.aQute.bnd"
            }
          ]
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins.source.formatter",
          "version": {
            "requires": "5.2.48"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins.target.platform",
          "version": {
            "requires": "3.0.15"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins.theme.builder",
          "version": {
            "requires": "2.0.25"
          },
          "excludes": [
            {
              "group": "biz.aQute.bnd",
              "module": "biz.aQute.bnd"
            }
          ]
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.petra.lang",
          "version": {
            "requires": "5.1.2"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.petra.string",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.portal.tools.bundle.support",
          "version": {
            "requires": "3.7.4"
          },
          "excludes": [
            {
              "group": "biz.aQute.bnd",
              "module": "biz.aQute.bnd"
            }
          ]
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.portal.tools.soy.builder",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "org.sonatype.plexus",
              "module": "*"
            },
            {
              "group": "org.codehaus.plexus",
              "module": "*"
            },
            {
              "group": "com.google.template",
              "module": "soy"
            }
          ]
        },
        {
          "group": "de.undercouch",
          "module": "gradle-download-task",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "net.saliman",
          "module": "gradle-properties-plugin",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "5.1"
          }
        }
      ],
      "files": [
        {
          "name": "com.liferay.gradle.plugins.workspace-999.0.0.jar",
          "url": "com.liferay.gradle.plugins.workspace-999.0.0.jar",
          "size": 399527,
          "sha512": "8b7bb29127ab84722f3868fc799b81534df71b5686f214d0b5d90a5720ab98948bc53b1e6920cfeec305b49d420f67c1bb5180ad9f5acaa5437526bd6a77f51f",
          "sha256": "565035191c9c2a04a8d1e4883f39e1ffae9e0dc408f0a18ae75b68648348b058",
          "sha1": "dac8733cf52b26d4ed85bee03e550450d9ecc5eb",
          "md5": "dcd05afeb779fd38210348f7077189a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "biz.aQute.bnd",
          "module": "biz.aQute.bnd.gradle",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.bmuschko",
          "module": "gradle-docker-plugin",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.github.docker-java",
          "module": "docker-java",
          "version": {
            "requires": "3.2.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.ant.bnd",
          "version": {
            "requires": "3.2.10"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins",
          "version": {
            "requires": "14.0.169"
          },
          "excludes": [
            {
              "group": "biz.aQute.bnd",
              "module": "biz.aQute.bnd"
            }
          ]
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins.css.builder",
          "version": {
            "requires": "5.0.10"
          },
          "excludes": [
            {
              "group": "biz.aQute.bnd",
              "module": "biz.aQute.bnd"
            }
          ]
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins.poshi.runner",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "biz.aQute.bnd",
              "module": "biz.aQute.bnd"
            }
          ]
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins.source.formatter",
          "version": {
            "requires": "5.2.48"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins.target.platform",
          "version": {
            "requires": "3.0.15"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.gradle.plugins.theme.builder",
          "version": {
            "requires": "2.0.25"
          },
          "excludes": [
            {
              "group": "biz.aQute.bnd",
              "module": "biz.aQute.bnd"
            }
          ]
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.petra.lang",
          "version": {
            "requires": "5.1.2"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.petra.string",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.portal.tools.bundle.support",
          "version": {
            "requires": "3.7.4"
          },
          "excludes": [
            {
              "group": "biz.aQute.bnd",
              "module": "biz.aQute.bnd"
            }
          ]
        },
        {
          "group": "com.liferay",
          "module": "com.liferay.portal.tools.soy.builder",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "org.sonatype.plexus",
              "module": "*"
            },
            {
              "group": "org.codehaus.plexus",
              "module": "*"
            },
            {
              "group": "com.google.template",
              "module": "soy"
            }
          ]
        },
        {
          "group": "de.undercouch",
          "module": "gradle-download-task",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "net.saliman",
          "module": "gradle-properties-plugin",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "5.1"
          }
        }
      ],
      "files": [
        {
          "name": "com.liferay.gradle.plugins.workspace-999.0.0.jar",
          "url": "com.liferay.gradle.plugins.workspace-999.0.0.jar",
          "size": 399527,
          "sha512": "8b7bb29127ab84722f3868fc799b81534df71b5686f214d0b5d90a5720ab98948bc53b1e6920cfeec305b49d420f67c1bb5180ad9f5acaa5437526bd6a77f51f",
          "sha256": "565035191c9c2a04a8d1e4883f39e1ffae9e0dc408f0a18ae75b68648348b058",
          "sha1": "dac8733cf52b26d4ed85bee03e550450d9ecc5eb",
          "md5": "dcd05afeb779fd38210348f7077189a1"
        }
      ]
    }
  ]
}
